// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/logo.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class logo {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=12;
      Object Q=$fix(GCollections.asSet("I","F","F1","ERROR","O1","R1","W1","A1","R2","L1","E1","F2","R3","I1","G1","H1","T1","R4","E2","P1","E3","A2"));
      $line=14;
      Object \u03A3=$fix(GCollections.asSet('f','d','$','o','r','w','a','l','e','f','t','i','g','h','t','p','t'));
      $line=15;
      Object q=$fix("I");
      $line=16;
      Object F=$fix(GCollections.asSet("F"));
      $line=18;
      GDeterministicAutomaton A=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(logo.class,"\u03B4")})));
      $line=19;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,logo.class,"main",$line);
    }
  }
  public static Object \u03B4(Object estado, Object comando) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=23;
      if ($opEqualY(estado,"I")) {
        $line=24;
        if ($opEqualY(comando,'f')) {
          $line=25;
          $result="F1";
          if (true) break $try;
        }
        else {
          $line=26;
          if ($opEqualY(comando,'l')) {
            $line=27;
            $result="L1";
            if (true) break $try;
          }
          else {
            $line=28;
            if ($opEqualY(comando,'$')) {
              $line=29;
              $result="F";
              if (true) break $try;
            }
            else {
              $line=30;
              if ($opEqualY(comando,'r')) {
                $line=31;
                $result="R3";
                if (true) break $try;
              }
              else {
                $line=33;
                $result="ERROR";
                if (true) break $try;
              }
            }
          }
        }
      }
      else {
        $line=37;
        if ($bool(estado.equals("F1"))) {
          $line=38;
          if ($opEqualY(comando,'d')) {
            $line=39;
            $result="I";
            if (true) break $try;
          }
          else {
            $line=40;
            if ($opEqualY(comando,'o')) {
              $line=41;
              $result="O1";
              if (true) break $try;
            }
            else {
              $line=43;
              $result="ERROR";
              if (true) break $try;
            }
          }
        }
        else {
          $line=45;
          if (($bool(estado.equals("O1"))&&$opEqualY(comando,'r'))) {
            $line=46;
            $result="R1";
            if (true) break $try;
          }
          else {
            $line=48;
            if ($bool(estado.equals("R1"))) {
              $line=49;
              if ($opEqualY(comando,'w')) {
                $line=50;
                $result="W1";
                if (true) break $try;
              }
              else {
                $line=52;
                $result="ERROR";
                if (true) break $try;
              }
            }
            else {
              $line=54;
              if ($bool(estado.equals("W1"))) {
                $line=55;
                if ($opEqualY(comando,'a')) {
                  $line=56;
                  $result="A1";
                  if (true) break $try;
                }
                else {
                  $line=58;
                  $result="ERROR";
                  if (true) break $try;
                }
              }
              else {
                $line=60;
                if ($bool(estado.equals("A1"))) {
                  $line=61;
                  if ($opEqualY(comando,'r')) {
                    $line=62;
                    $result="R2";
                    if (true) break $try;
                  }
                  else {
                    $line=64;
                    $result="ERROR";
                    if (true) break $try;
                  }
                }
                else {
                  $line=66;
                  if ($bool(estado.equals("R2"))) {
                    $line=67;
                    if ($opEqualY(comando,'d')) {
                      $line=68;
                      $result="I";
                      if (true) break $try;
                    }
                    else {
                      $line=70;
                      $result="ERROR";
                      if (true) break $try;
                    }
                  }
                  else {
                    $line=74;
                    if (($bool(estado.equals("L1"))&&$opEqualY(comando,'e'))) {
                      $line=75;
                      $result="E1";
                      if (true) break $try;
                    }
                    else {
                      $line=76;
                      if (($bool(estado.equals("E1"))&&$opEqualY(comando,'f'))) {
                        $line=77;
                        $result="F2";
                        if (true) break $try;
                      }
                      else {
                        $line=78;
                        if (($bool(estado.equals("F2"))&&$opEqualY(comando,'t'))) {
                          $line=79;
                          $result="I";
                          if (true) break $try;
                        }
                        else {
                          $line=81;
                          if ($bool(estado.equals("R3"))) {
                            $line=82;
                            if ($opEqualY(comando,'i')) {
                              $line=83;
                              $result="I1";
                              if (true) break $try;
                            }
                            else {
                              $line=84;
                              if ($opEqualY(comando,'e')) {
                                $line=85;
                                $result="E2";
                                if (true) break $try;
                              }
                              else {
                                $line=87;
                                $result="ERROR";
                                if (true) break $try;
                              }
                            }
                          }
                          else {
                            $line=90;
                            if (($bool(estado.equals("I1"))&&$opEqualY(comando,'g'))) {
                              $line=91;
                              $result="G1";
                              if (true) break $try;
                            }
                            else {
                              $line=92;
                              if (($bool(estado.equals("G1"))&&$opEqualY(comando,'h'))) {
                                $line=93;
                                $result="H1";
                                if (true) break $try;
                              }
                              else {
                                $line=95;
                                if (($bool(estado.equals("H1"))&&$opEqualY(comando,'t'))) {
                                  $line=96;
                                  $result="I";
                                  if (true) break $try;
                                }
                                else {
                                  $line=99;
                                  if (($bool(estado.equals("E2"))&&$opEqualY(comando,'p'))) {
                                    $line=100;
                                    $result="P1";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=101;
                                    if (($bool(estado.equals("P1"))&&$opEqualY(comando,'e'))) {
                                      $line=102;
                                      $result="E3";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=103;
                                      if (($bool(estado.equals("E3"))&&$opEqualY(comando,'a'))) {
                                        $line=104;
                                        $result="A2";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=105;
                                        if (($bool(estado.equals("A2"))&&$opEqualY(comando,'t'))) {
                                          $line=106;
                                          $result="I";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=108;
                                          $result="ERROR";
                                          if (true) break $try;
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=110;
      $rethrow(new RuntimeException("The function \"\u03B4(estado:Object,comando:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,logo.class,"\u03B4",$line);
    }
    return $result;
  }
}
