// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/NewFile.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class NewFile {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=13;
      Object Q=$fix(GCollections.asSet("A","B","C","D"));
      $line=14;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=15;
      Object q=$fix("A");
      $line=16;
      Object F=$fix(GCollections.asSet("A","B","C"));
      $line=18;
      GDeterministicAutomaton A=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(NewFile.class,"\u03B4")})));
      $line=19;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,NewFile.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=23;
      if (($opEqualY(q,"A")&&$opEqualY(\u03C3,'1'))) {
        $line=24;
        $result="B";
        if (true) break $try;
      }
      else {
        $line=25;
        if (($opEqualY(q,"B")&&$opEqualY(\u03C3,'1'))) {
          $line=26;
          $result="C";
          if (true) break $try;
        }
        else {
          $line=27;
          if (($opEqualY(q,"C")&&$opEqualY(\u03C3,'1'))) {
            $line=28;
            $result="D";
            if (true) break $try;
          }
          else {
            $line=29;
            if ($opEqualY(q,"D")) {
              $line=30;
              $result="D";
              if (true) break $try;
            }
            else {
              $line=31;
              if ($opEqualY(\u03C3,'0')) {
                $line=32;
                $result="A";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=34;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,NewFile.class,"\u03B4",$line);
    }
    return $result;
  }
}
