// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Transductores.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Transductores {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=4;
      Object Estados=$fix(GCollections.asSet(0,1));
      $line=5;
      Object Input=$fix($opIntvlY('a','b'));
      $line=6;
      Object Output=$fix(Input);
      $line=7;
      Object inicial=$fix(0);
      $line=8;
      Object Finales=$fix(GCollections.emptySet());
      $line=10;
      Object T=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Estados,Input,Output,inicial,Finales,new GMethod(Transductores.class,"transiciones"),new GMethod(Transductores.class,"imprEstados"),new GMethod(Transductores.class,"imprFlechas")}));
      $line=13;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,T));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Transductores.class,"main",$line);
    }
  }
  public static Object transiciones(Object estado, Object simbolo) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=17;
      if ($opEqualY(estado,0)) {
        $line=18;
        $result=1;
        if (true) break $try;
      }
      else {
        $line=21;
        $result=0;
        if (true) break $try;
      }
      $line=24;
      $rethrow(new RuntimeException("The function \"transiciones(estado:Object,simbolo:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Transductores.class,"transiciones",$line);
    }
    return $result;
  }
  public static Object imprFlechas(Object estado, Object simbolo) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=27;
      if ($opEqualY(estado,0)) {
        $line=28;
        $result=simbolo;
        if (true) break $try;
      }
      else {
        $line=30;
        if ($opEqualY(simbolo,'a')) {
          $line=31;
          $result="b";
          if (true) break $try;
        }
        else {
          $line=34;
          $result="a";
          if (true) break $try;
        }
      }
      $line=39;
      $rethrow(new RuntimeException("The function \"imprFlechas(estado:Object,simbolo:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Transductores.class,"imprFlechas",$line);
    }
    return $result;
  }
  public static Object imprEstados(Object estado) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=42;
      $result="";
      if (true) break $try;
      $line=43;
      $rethrow(new RuntimeException("The function \"imprEstados(estado:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Transductores.class,"imprEstados",$line);
    }
    return $result;
  }
}
